// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuexemxndosbvoghbhce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1ZXhlbXhuZG9zYnZvZ2hiaGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTYyNjYsImV4cCI6MjA1NTUzMjI2Nn0.zOc9eiJ6JAwGjylE9ymbm8RFW0ewy3iagVekYeDnMEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);